name: Test package MacOS

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["main", "tester/*"]
  pull_request:
    branches: ["main"]

jobs:
  test-package:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        name: [
          "macos-python-3-10",
          "macos-python-3-11",
          "macos-python-3-12",
          "macos-python-3-13"
        ]

        include:
          - name: "macos-python-3-10"
            python-version: "3.10"
            os: macos-latest
          - name: "macos-python-3-11"
            python-version: "3.11"
            os: macos-latest
          - name: "macos-python-3-12"
            python-version: "3.12"
            os: macos-latest
          - name: "macos-python-3-13"
            python-version: "3.13"
            os: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build package
      run: python -m pip install -e .
    - name: Install test requirements
      run: python -m pip install unittest-extensions
    - name: Test package
      run: python -m unittest -v test.py